#!/bin/sh

labelrootfs_enabled() {
    return 0
}

labelrootfs_run() {
    echo "Waiting for udev to populate /dev/disk/by-label/$bootparam_LABEL... "
    while :
    do
        if test -e /dev/disk/by-label/$bootparam_LABEL; then
            break
        fi
        sleep 1
    done
    echo "Found $bootparam_LABEL label."

    bootparam_root="/dev/disk/by-label/$bootparam_LABEL"
}
