#!/bin/sh

set -e

FLASHER_CONF_FILE=/etc/resin-init-flasher.conf
INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT=/tmp/internal_boot
CURRENT_ROOT=$(findmnt --noheadings --canonicalize --output SOURCE / | xargs lsblk -no pkname)

# source the flasher configuration file
if [ -f $FLASHER_CONF_FILE ]; then
    source $FLASHER_CONF_FILE
else
    echo "No configuration for resin-init-flasher-board. Cannot configure bootloader. Exiting"
    exit 1
fi

if efibootmgr &>/dev/null ; then 
    INSTALL_UEFI="yes"
fi

# Mount internal device boot partition
mkdir -p $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
echo "[resin-init-flasher-board] Mounting internal device boot partition."
if ! mount /dev/disk/by-label/resin-boot $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT; then
    echo "[resin-init-flasher-board] Unable to mount boot partition"
    exit 1
fi

internal_dev=""
for d in $INTERNAL_DEVICE_KERNEL; do
    if [ "$CURRENT_ROOT" = "$d" ]; then
        echo "[resin-init-flasher-board] $d is our install media, skip it..."
        continue
    fi
    if [ -b "/dev/$d" ]; then
        internal_dev=$d
        break
    fi
done

if [ -z "$internal_dev" ]; then
    echo "Failed to find internal device for which to configure the bootloader. Exiting"
    exit 1
fi

if [ -z $INSTALL_UEFI ]; then
    echo "[resin-init-flasher-board] non-UEFI installation."
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
else
    echo "[resin-init-flasher-board] UEFI installation."
    dd if=/dev/zero of=/dev/$internal_dev bs=1 count=446
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
fi

umount $INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT
sync

[ -z $INSTALL_UEFI ] && exit 0

echo "Add UEFI boot entry for starting resinOS from internal media."
efibootmgr -c -d /dev/$internal_dev -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi"

exit 0
