#!/bin/sh

set -o errexit

verifyMd5sum() {
  if [ "$1" = "$3" ] ; then return 1; fi
}

getSize() {
  echo $(du -sb "$1" | awk '{print $1}')
}

MBR=512
reservedMBR=66
sourcePath="/resin-boot/grub/"
device="/dev/$(findmnt --noheadings --canonicalize --output SOURCE /mnt/sysroot/active | xargs lsblk -no pkname)"

firstBootloader=boot.img
secondBootloader=core.img

md5sum_diskFirstBootloader=$(dd if=$device bs=1 count=$(getSize "$sourcePath$firstBootloader") | md5sum)
md5sum_diskSecondBootloader=$(dd if=$device skip=$MBR bs=1 count=$(getSize "$sourcePath$secondBootloader") | md5sum)

if verifyMd5sum $(md5sum $sourcePath$firstBootloader) $md5sum_diskFirstBootloader; then
  dd if="$sourcePath$firstBootloader" of="$device" conv=fdatasync bs=1 count=$(expr $MBR - $reservedMBR)
fi
if verifyMd5sum $(md5sum $sourcePath$secondBootloader) $md5sum_diskSecondBootloader; then
  dd if="$sourcePath$secondBootloader" of="$device" conv=fdatasync bs=1 seek=$MBR
fi
