#!/bin/sh

set -e

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-logging

FLASHER_CONF_FILE=/etc/resin-init-flasher.conf
INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT=/tmp/internal_boot
CURRENT_ROOT=$(findmnt --noheadings --canonicalize --output SOURCE / | xargs lsblk -no pkname)

# source the flasher configuration file
if [ -f $FLASHER_CONF_FILE ]; then
    source $FLASHER_CONF_FILE
else
    fail "No configuration for resin-init-flasher-board. Cannot configure bootloader. Exiting"
fi

if efibootmgr &>/dev/null ; then 
    INSTALL_UEFI="yes"
fi

# Internal device boot partition already mounted in flasher script
if ! findmnt --noheadings -M "${INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT}" > /dev/null 2>&1; then
    fail "[resin-init-flasher-board] Boot partition not mounted"
fi

internal_dev=""
for d in $INTERNAL_DEVICE_KERNEL; do
    if [ "$CURRENT_ROOT" = "$d" ]; then
        info "[resin-init-flasher-board] $d is our install media, skip it..."
        continue
    fi
    if fdisk -l | grep -q "$d"; then
        internal_dev=$d
        break
    fi
done

if [ -z "$internal_dev" ]; then
    fail "Failed to find internal device for which to configure the bootloader. Exiting"
fi

if [ -z $INSTALL_UEFI ]; then
    info "[resin-init-flasher-board] non-UEFI installation."
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/EFI"
else
    info "[resin-init-flasher-board] UEFI installation."
    dd if=/dev/zero of=/dev/$internal_dev bs=1 count=446
    rm -rf "$INTERNAL_DEVICE_BOOT_PART_MOUNTPOINT/grub"
fi

sync

[ -z $INSTALL_UEFI ] && exit 0

# remove existing resinOS entries so we won't have duplicates
if ! mount | grep efivarfs > /dev/null; then mount -t efivarfs efivarfs /sys/firmware/efi/efivars; fi
duplicates=`efibootmgr | grep resinOS |sed 's/Boot*//g' | sed 's/* resinOS//g'`
for i in $duplicates; do efibootmgr -B -b $i; done

info "Add UEFI boot entry for starting resinOS from internal media."
efibootmgr -c -d /dev/$internal_dev -p 1 -L "resinOS" -l "\EFI\BOOT\bootx64.efi"

exit 0
