name: Generic x86_64 (legacy MBR)

on:
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
  pull_request:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+
  pull_request_target:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+
  push:
    branches:
      - main
      - master
      # ESR branches glob pattern
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+
    tags:
      # Semver tags glob pattern (includes ESR in format v20YY.MM.PATCH)
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy-s3:
        description: Deploy artifacts to S3?
        required: false
        type: boolean
        default: true
      deploy-hostapp:
        description: Deploy hostApp to balenaCloud?
        required: false
        type: boolean
        default: true
      deploy-esr:
        description: Deploy as an ESR release?
        required: false
        type: boolean
        default: false
      os-dev:
        description: Enable OS development features
        required: false
        type: boolean
        default: false

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@7b65acc0280a2239d7f8fcfd7260151d97b6f3d5 # v1.25.9
    # Prevent duplicate workflow executions for pull_request (PR) and pull_request_target (PRT) events.
    # Both PR and PRT will be triggered for the same pull request, whether it is internal or from a fork.
    # This condition will prevent the workflow from running twice for the same pull request while
    # still allowing it to run for all other event types.
    if: (github.event.pull_request.head.repo.full_name == github.repository) == (github.event_name == 'pull_request')
    secrets: inherit
    with:
      machine: genericx86-64-ext
      # Use qemu workers for testing
      test_matrix: >
        {
          "test_suite": ["os","cloud","hup"],
          "environment": ["bm.balena-dev.com"],
          "worker_type": ["qemu"],
          "runs_on": [["self-hosted", "X64", "kvm"]]
        }
      # Keep these undefined for push/pull_request events to use workflow defaults
      deploy-s3: ${{ inputs.deploy-s3 }}
      deploy-hostapp: ${{ inputs.deploy-hostapp }}
      deploy-esr: ${{ inputs.deploy-esr }}
      os-dev: ${{ inputs.os-dev }}
